springdoc:
  api-docs:
    path: /api-docs
aws:
  default:
    region: us-east-2
  access:
    access-key: AKIAZK2JA2ZMTRFSMRFK
    secret-key: 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
    service-endpoint: dynamodb.us-east-2.amazonaws.com
  cognito:
    clientId : 1pkm2c3gg6s83t8a72bdcmdeti
    userPoolId: us-east-2_UtujH4zQk
    region: us-east-2
    connectionTimeOut: 200
    readTimeOut: 2000
    jwk: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_UtujH4zQk/.well-known/jwks.json
    