springdoc:
  api-docs:
    path: /api-docs
aws:
  default:
    region: us-east-2
  access:
    access-key: AKIA5Z6LZFXPAWUQ2LFZ
    secret-key: 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
    service-endpoint: dynamodb.us-east-2.amazonaws.com
  cognito:
    clientId : 277kjuq3rnq4uu13ub0mo2m8j9
    userPoolId: us-east-2_VwNQ8ewTR
    region: us-east-2
    connectionTimeOut: 200
    readTimeOut: 2000
    jwk: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_UtujH4zQk/.well-known/jwks.json
    