package com.samy.service.cognitoapp.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.samy.service.cognitoapp.config.LocalDateTimeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "seguimiento")
@Getter
@Setter
@NoArgsConstructor
@ToString
public class Seguimiento implements Serializable {

  private static final long serialVersionUID = -699586199289976697L;

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  @DynamoDBAttribute(attributeName = "id_seguimiento")
  private String idSeguimiento;

  @DynamoDBAttribute
  private String accion;

  @DynamoDBAttribute
  private String datosCompletos;

  @DynamoDBAttribute
  private String empresa;

  @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
  @DynamoDBAttribute
  private LocalDateTime fechaIngreso;

  @DynamoDBAttribute
  private String idUsuario;

  @DynamoDBAttribute
  private String tipo;

  @DynamoDBAttribute
  private String usuario;

}
